### ISSUE TITLE
[BUG] Whitelisting sub-packages

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposed#115]
I'm having an issue with whitelisting sub-packages (probably a better name for this).
For example - 

I'm whitelisting `com.android.settings` which appears in the whitelist list.
But this app also has a package named `com.samsung.android.settings`, which doesn't appear in the whitelist list.
When I want to hook methods that are in `com.samsung.android.settings` I need to find them in the `com.android.settings` classLoader.

Hooks that use `com.android.settings` work, but those who call `com.samsung.android.settings` don't.

**Comment by solohsu** [comment]
`com.android.settings` shown in whitelist list is applicationId. And in its APK file, there are arbitrary packages, e.g. `com.samsung.android.settings` in your case.
Xposed calls your handleLoadPackage callbacks using applicationId, but not the package name of the methods you want to hook.

**Comment by Firefds** [comment]
Exactly. Is there a way to whitelist the arbitrary packages?

**Comment by solohsu** [comment]
Sorry, I can't get your point. So this is not a bug but a feature propose?
Why would you need this?

**Comment by Firefds** [comment]
Yes, it could be a feature propose.

It could be usefull for users who want to whitelist certain apps and have xposed modules who use 
arbitrary packages, like the one I'm building.

You can look here for an example:

https://github.com/Firefds/FirefdsKit/blob/pie/app/src/main/java/sb/firefds/pie/firefdskit/XSecSettingsPackage.java
Which is called by
https://github.com/Firefds/FirefdsKit/blob/pie/app/src/main/java/sb/firefds/pie/firefdskit/Xposed.java

The hooks inside `XSecSettingsPackage` use `com.samsung.android.settings`, and the class is loaded only when the applicationId is `com.android.settings`

**Comment by solohsu** [comment]
I think your codes would work with no problem. I can't figure out what's the problem.
Actually black/white list was introduced to prevent some apps who detect xposed stuffs from crashing by not injecting xposed related stubs into blacklisted processes. So the granularity is process.
If your want to hook methods under `com.samsung.android.settings` package, you have to check `com.android.settings` in whitelist list if you are using whitelist mode.
In other cases I don't recommend use of black/white list.

**Comment by XspeedPL** [comment]
This doesn't make much sense. As far as I know the whitelist operates on application package names, not class package names.

**Comment by Firefds** [comment]
@soloshu that's exactly what I'm doing, and it doesnt work (hooks dont go through to 'com.samsung.android.settings'

**Comment by solohsu** [comment]
@Firefds You mean `XSecSettingsPackage#doHook` not called or `Packages.SAMSUNG_SETTINGS + ".bluetooth.BluetoothScanDialog"` such class can't be found?

**Comment by Firefds** [comment]
@solohsu I tested this now.
First of all - XposedBridge log doesn't seem to work when whitelisting. I had to add Log call to the code.

These are all the applications I whitelisted
![2019-03-01 08 15 49](https://user-images.githubusercontent.com/18083277/53620150-90e06a80-3bfa-11e9-8e0a-3c859a90080f.jpg)

From this list, the only ones that are recognized (as in `lpparam.packageName.equals(PACKAGENAME)`) are:
com.samsung.android.email.provider
com.sec.android.app.camera
com.android.systemui
sb.firefds.pie.firefdskit

The reset are not called.

The youtube xposed modal also works, and I'm guessing the EdXposed Installer as well.

**Comment by XspeedPL** [comment]
This is now a different topic from your first post.
Handle load package hook deals ONLY with application package names. You won't see "com.samsung.android.settings" logged in lpparams.

Also, not all whitelisted packages are displayed at all times, because system only loads the packages when they are explicitly needed, in example an application is run by user. Hence some packages may not always be loaded, or they may be loaded multiple times.

**Comment by solohsu** [comment]
@Firefds I can confirm this issue exists which is that when using black/white list mode, edxposed's bootstrap hooks cannot be installed into some system app processes because [Riru-core filters their uids](https://github.com/RikkaApps/Riru/blob/34f845c846e3f3b3ca21cdf8dc8c666241c7304f/riru-core/jni/main/jni_native_method.cpp#L28).
I managed to solve this by adding a new riru module api:
https://github.com/solohsu/Riru/commit/9a382b03a3e5b7bdfc8d7ada209feebfe6a6d473
https://github.com/ElderDrivers/EdXposed/commit/ff595542c4c1baca70ac5f17f1d6ff0f03934858
And here are the latest builds:
[magisk-riru-core-v15-mod.zip](https://github.com/ElderDrivers/EdXposed/files/2920712/magisk-riru-core-v15-mod.zip)
[magisk-EdXposed-v0.2.9.9_beta3-SNAPSHOT.zip](https://github.com/ElderDrivers/EdXposed/files/2920719/magisk-EdXposed-v0.2.9.9_beta3-SNAPSHOT.zip)

**Comment by rxzcums** [comment]
刚刚测试了上面2个附件，发现我之前提过的一个issuse又回来了：
https://github.com/ElderDrivers/EdXposed/issues/83
我目前在0.2.9.9.b2，从0.2.9.9.b1起，这个issuse是已修复了的。
请@solohsu帮助。

**Comment by Firefds** [comment]
@solohsu this seems to have fixed the issue, and the arbitrary packages are hooked as well.
Thank you!
