### ISSUE TITLE
[Discussion] Use XSharedPreferences on Android Pie

### ISSUE THREAD

**Issue by Ninlives** [ElderDrivers/EdXposed#260]
Android Pie introduces a new security mechanism that breaks the normal usage of XSharedPreferences.
So far I've found three workarounds to read Xposed module's preferences in the hooked application's process on Pie and each of them has some limitations:
1. Write preferences file to external storage, which requires users to grant permissions of accessing external storage for all hooked applications(Am I right?)
2. Export preferences using a Content Provider (https://github.com/apsun/RemotePreferences), can't use it directly in `handleLoadPackage` because the application context is not initialized yet.
3. Using SharedPreferences normally and manually set the `data`, `shared_prefs` directory and the pref file itself to be world-readable. The API version cannot be higher than 26 otherwise Android Pie will set SELinux rules and other applications cannot read the pref file.

Do you have a better solution? Or can we bypass the security mechanism by using, e.g. magiskpolicy to disable the restrictions of accessing data files for all Xposed modules?

**Comment by C3C0** [comment]
Question whether your module needs to reload preferences during runtime when you change them or if it is enough to read them at boot. If you don't need them to be changed during runtime just initialize static variable holding XSharedPreferences during initZygote and they will propagate to all subsequent handleLoadPackage calls automatically (as processes will inherit that static variable from zygote process).
For this to work you have to make sure you are using [Device protected storage](https://developer.android.com/reference/android/content/Context.html#createDeviceProtectedStorageContext()) for your preference files since you have to make sure zygote process has access to them.
(Normal app data storage on File Based Encryption devices are accessible only after user authenticates).

EdXposed already comes with the basic set of SELinux rules to allow zygote (and other platform apps) to access data directory of another app. You don't need to restrict yourself to SDK 26 but you need to make sure permissions of your module data directory as well as shared_prefs and related xmls are readable for all. Android proactively adjusts permissions of preference xmls after committing changes so you have to readjust. There are several strategies you can use. E.g. in onPause of your module settings app or you can even use a File Observer to listen to file attribute changes and readjust permissions immediately when they get changed.

**Comment by Ninlives** [comment]
Hi @C3C0 thanks for your reply!
So if I understand correctly, I can read the module data directory in `initZygote` even the SDK is higher than 27 but if I want to reload the preferences I have to reboot the device?

**Comment by C3C0** [comment]
Yes. And in case you also need reloading functionality, you can solve it by using broadcast intents.
E.g. you register broadcast receiver within package you are hooking to receive intents sent from your module settings app whenever you change a setting.

**Comment by Ninlives** [comment]
Got it, thanks for your quick reply!

**Comment by Ninlives** [comment]
Will the unimplemented "File Access Service" mentioned in the README help to achieve this? Is it on the roadmap?

**Comment by Mikanoshi** [comment]
Read all here :)
https://github.com/ElderDrivers/EdXposed/issues/149
Actually if you need to reload preferences on the fly you can implement world readable shared prefs (see class in GravityBox, just a regular SharedPreferences with FileObserver that listens to xml attrib changes and fixes permissions). Then XSharedPreferences.reload() should work.
