### ISSUE TITLE
[BUG] Conflicting with other magisk modules

### ISSUE THREAD

**Issue by damadikaz** [ElderDrivers/EdXposed#265]
**什么情况/What happened?**
Riru - EdXposed causes other Magisk module to behave strangely. Like Substratum applied overlay being disabled, Viper4andrid and YT vanced display welcome window and asks permission after every reboot, the same happen with Google's Wallpaper apps that I systemized it using App Systemizer. According to Magisk Support thread: "... EdXposed seems to break the Magisk boot process on some devices. The late_start service mode runs too early (or magic mounting happens too late, not entirely sure which). It needs to be brought up with the EdXposed developer, ..." I ran EdXposed without any modules, the problem still persist. 

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
-no full screen keyboard (disabled)

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
-busybox NDK
-QuickSwitch
-Riru core
-Riru EdXposed
-Substratum
-Viper4android
-YT vanced

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.1.2_beta(SandHook)

Riru: v19

**相关Logcat/Logcat**
-getting the logcat

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by dp-alvarez** [comment]
@solohsu and @MlgmXyysd
Have you guys been able to take a look at this? It breaks a lot of other Magisk modules, so it is quite an annoying bug!
I can help with debugging if needed, just let me know which details you need.

**Comment by MlgmXyysd** [comment]
I haven't encountered any of these problems, and many of my modules are working properly.
can u provide your device infomation?

**Comment by dp-alvarez** [comment]
I'm on a Mi5 with lineage-16.0-20190613. The problem appears when using the NanoDroid module, all settings of system apps are reset on reboot.
This only happens when using EdXposed, regardless of any modules enabled. Riru by itself causes no problems.

Based on https://github.com/ElderDrivers/EdXposed/issues/287#issuecomment-501537115 it seems like the problem is in https://github.com/ElderDrivers/EdXposed/blob/master/edxp-core/template_override/common/post-fs-data.sh

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/issues/287#issuecomment-508850704
It seems it was fixed?
