### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Moderndaycowboy** [ElderDrivers/EdXposed#285]
Wanna ask 3 question to make it clear.

1- does it slow the phone or create lag?

2- does it extend the boot time?

3- does it break safety net?

Thank you.

**Comment by DanGLES3** [comment]
1-depending on the module then yes (the performance impact is dependent on the nodules),
2-a little bit since it needs to inject into the zygote process during boot time,the sandhook version tends to boot up faster than the yahfa version tho
3-edxposed was designed to not break safetynet as we're not replacing zygote like the original xposed but rather we're using Riru to inject into zygote making detection by safety net much more difficult

**Comment by NewBugger** [comment]
1/sure  
2/sure  
3/no, compared with Original Xposed, it's a great feature.

**Comment by zhangwilling** [comment]
i want know if there is a way to debug my xp module without restart my phone. in original xposed, i know some tricks to do some experiment without restart.
我想咨询一下，在edxposed方案下，如何做到免重启调试我的xp模块。在原始xp下，我知道几种方式可以做到免重启调试
