### ISSUE TITLE
[BUG] safety net fails on and when run edxposed manager now gets passed.

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposed#435]
**什么情况/What happened?**
Safetynet failed after reboot everytime but when i run edxposed manager and again goto magisk it will be passed and this is random sometimes fails sometime passes even without reboot

Samsung galaxy note 9 android 10

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru** 19.6

EdXposed: 0.4.6.1 build 4491

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

Dont know why logs has no issues

The only error edxposed keeps showing is this

01-07 17:04:14.148  4913  4913 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/150/com.google.android.gsf
01-07 17:04:14.148  4913  4913 E EdXposed: can't access config path, using snapshot black list: /data/user/150/com.google.android.gsf

And this shows for all apps for example play store, calender, play services etc

**Comment by Jasi2169** [comment]
Just tell me what is needed i will provide

**Comment by MlgmXyysd** [comment]
01-07 17:04:14.148 4913 4913 E EdXposed: can't access config path, using snapshot black list: /data/user/150/com.google.android.gsf

**Comment by ayush7gl** [comment]
@Jasi2169 hey, i also facing same issue. Have you found any solution??

**Comment by Senliast** [comment]
I also have this issue, latest EdXposed, Android 10. Because of this, Google Pay stops working sometimes. Please fix it, it is very annoying!

**Comment by adrijshikhar** [comment]
I am on Oneplus7 stock with latest riru and edxposed.
safetynet check failed whenever i enable riru and edxposed module.

**Comment by SoumyBhow** [comment]
This is a multi user issue, right? Do things like Oneplus' Parallel Apps cause this? Isn't this fixed in the newer versions of Edxposed Canary? I have to use the 4.6.5 Snapchat version because I have Snapchat, so I can't test it myself...

**Comment by drewcu** [comment]
The latest Canary 4527 with the "Replace cmdline to pass SafetyNet" has more SN issues for me than Canary 4524 on my LG V30. 

When Google updated their SN tests and so many people's unlocked phones failed, my V30 did not. It still passes with Edxposed Manager's Pass SN/App Mode, but only after a few minutes post-startup, and will fail initially, then pass later on when I clear all open apps.

But with 4527, it fails most of the time and only passed for a couple minutes when I randomly tested, but then failed soon after. I have gone back to 4524 which seems to pass SN more often and don't know what was fixed in 4527 but was not for my benefit.

**Comment by MlgmXyysd** [comment]
@drewcu Okay, maybe I should write the replacement script completely

**Comment by cscomic** [comment]
Same problem here, sony xperia xz1 with Android oreo.

**Comment by YourYoungerBrothersPug** [comment]
I'm rocking Android 10 on my Moto G5+ and Android 9 on my Moto G4+, and when installing the 4527 or 4529 Canary build in Magisk, it's just "flashing" constantly. When in Recovery, it doesn't like extracting the zip file. Downloaded twice and it doesn't like it. Also, looking at 4529 build does installing SafetyPatcher just do it, you don't need to configure it? Thanks - Josh

**Comment by Senliast** [comment]
@drewcu which modules do you use?

**Comment by drewcu** [comment]
Edxposed: Gravitybox, Bootmanager, Lucky Patcher, Maps tweaks, Minminguard, XinternalSD

**Comment by drewcu** [comment]
> @drewcu Okay, maybe I should write the replacement script completely

What's the difference between 4529 and 4530? I could pass SafetyNet with 4529 and cannot with 4530, so I am reverting back to 4529. Both say they are reverting SN changes.

**Comment by SoumyBhow** [comment]
I'm using the 4.6.5 Snapchat version of Edxposed and I'm also failing SafetyNet. This doesn't look good...

**Comment by drewcu** [comment]
> I'm using the 4.6.5 Snapchat version of Edxposed and I'm also failing SafetyNet. This doesn't look good...

Were you passing SN as recently as yesterday? What phone do you have?

**Comment by SoumyBhow** [comment]
> > I'm using the 4.6.5 Snapchat version of Edxposed and I'm also failing SafetyNet. This doesn't look good...
> 
> Were you passing SN as recently as yesterday? What phone do you have?

I don't remember if I was passing SN yesterday (I think I was). Running a OnePlus 7 Pro with OOS 10.3.2.

**Comment by drewcu** [comment]
Just was making sure you've passed since Google modified SN and so many others had their tests fail. Thought I was in the clear but I guess they cracked down on the remaining phones like ours.

**Comment by SoumyBhow** [comment]
> Just was making sure you've passed since Google modified SN and so many others had their tests fail. Thought I was in the clear but I guess they cracked down on the remaining phones like ours.

I think it's an Edxposed thing. When I disabled Edxposed SN passed again. I do hope someone finds a solution. Thankfully I'm not using any apps that really depend on SN.

**Comment by fgprodigal** [comment]
some issue, passed yesterday, but failed now. It will pass when i disable the edxposed

**Comment by MlgmXyysd** [comment]
#500

**Comment by drewcu** [comment]
@MlgmXyysd Closing this ticket doesn't take away from the fact that many of us still can PASS SafetyNet when Edxposed is DISABLED -- myself included I've realized now. Others fail SafetyNet because of Google's SN updates even when Edxposed is disabled. Thus there is something about Edxposed that is causing Safetynet to fail now when it passed a couple of days ago. Please look into this for the many people like myself whose devices are not completely blacklisted at Google.

Thank you!

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd Closing this ticket doesn't take away from the fact that many of us still can PASS SafetyNet when Edxposed is DISABLED -- myself included I've realized now. Others fail SafetyNet because of Google's SN updates even when Edxposed is disabled. Thus there is something about Edxposed that is causing Safetynet to fail now when it passed a couple of days ago. Please look into this for the many people like myself whose devices are not completely blacklisted at Google.
> 
> Thank you!

Passing is only temporary, I have accepted topjohnwu's suggestion and no longer accept any feedback on SafetyNet

**Comment by drewcu** [comment]
@MlgmXyysd Sorry to hear that because topjohnwu even acknowledged that NOT everyone is failing SafetyNet like us. See: https://twitter.com/topjohnwu/status/1237656704537395201

When I disabled Edxposed, suggested by @SoumyBhow, I was able to pass SafetyNet consistently every time I tried it. 

Would greatly appreciate if you could not give up on those of us who still have some hope of using Edxposed alongside a working SafetyNet.

Thank you!

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd Sorry to hear that because topjohnwu even acknowledged that NOT everyone is failing SafetyNet like us. See: https://twitter.com/topjohnwu/status/1237656704537395201
> 
> When I disabled Edxposed, suggested by @SoumyBhow, I was able to pass SafetyNet consistently every time I tried it.
> 
> Would greatly appreciate if you could not give up on those of us who still have some hope of using Edxposed alongside a working SafetyNet.
> 
> Thank you!

I don't want to give up on you either, I'm trying to rename the module's library randomly to hide frame features, hope this works

**Comment by drewcu** [comment]
With 4532 Sandhook, SafetyNet works again on my LG V30! I still don't pass every time I run the test, but that was the case before it stopped working completely, too. But unlike 4530, if it fails initially, it does indeed usually pass if I close all apps and open Magisk again and test it. 

Well done, thanks Jim!

**Comment by drewcu** [comment]
Back to failing SafetyNet with 4544 Sandhook on my LG V30... 
Cat and mouse game with Google. 

@MlgmXyysd -- any chance you can work your magic on this again? 

Many thanks!

**Comment by Adrian-at-CrimsonAuzre** [comment]
4545 Sandhook worked for me on my OnePlus 7 Pro. SafetyNet is back to passing and Google Pay is working.

Thanks for fixing it.

**Comment by SoumyBhow** [comment]
> Back to failing SafetyNet with 4544 Sandhook on my LG V30... 
> Cat and mouse game with Google. 
> 
> @MlgmXyysd -- any chance you can work your magic on this again? 
> 
> Many thanks!

Did you try clearing data and cache of Google Play Store and Google Play Services and reboot?

**Comment by Adrian-at-CrimsonAuzre** [comment]
> Did you try clearing data and cache of Google Play Store and Google Play Services and reboot?

Apparently you don't _need_ to while data, just cache. If just cache doesn't work, then wipe data as well.

**Comment by drewcu** [comment]
> > Back to failing SafetyNet with 4544 Sandhook on my LG V30...
> > Cat and mouse game with Google.
> > @MlgmXyysd -- any chance you can work your magic on this again?
> > Many thanks!
> 
> Did you try clearing data and cache of Google Play Store and Google Play Services and reboot?

@SoumyBhow and @Adrian-at-CrimsonAuzre -- thank you that worked! 

Thought all was lost when I disabled EdXposed and still couldn't pass SafetyNet, but I re-enabled it again and cleared Google Play Store's Data and voila -- I can pass SafetyNet again!

I did clear cache on Google Play Services earlier but that didn't do anything. I have an Android Wear  watch which gets borked if I clear data on GPS so I only do that as last resort.

So it seems clearing the Play Store data is sufficient (possibly even just the cache which I didn't try since it's so easy to restore the Store's settings).

Thanks again!
