### ISSUE TITLE
[BUG] SafetyNet fails after a few hours after boot

### ISSUE THREAD

**Issue by Senliast** [ElderDrivers/EdXposed#491]
**什么情况/What happened?**

SafetyNet fails after a few hours after the phone boots. Only a restart helps, and then it happens again in a few hours. Without EdXposed, it passes just without problems. Android 10, latest
EdXposed v0.4.6.1.410 Yahfa, Evolution X ROM.

**Xposed模块列表/Xposed Module List**

GravityBox, Jasi Patcher, Lucky Patcher, XPrivacy Lua, DisableFlagSecure, App Locale 2

**Magisk模块列表/Magisk Module List**

BusyBox for Android NDK, Google Product Sans, GPay SQLite Fix, Magisk Hide Props Config,
Riru - core, Riru - EdXposed, SQLite, substratum, Systemless Hosts, YouTube Vanced.

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.1.410 Yahfa

Riru: 19.7

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
@Senliast Since Google updated SafetyNet, we not allow any SafetyNet issues

Reference: 
https://t.me/EdXposed/71
https://github.com/topjohnwu/Magisk/commit/612b51d48f9771a65cfab045f931573f42d3a494
https://twitter.com/topjohnwu/status/1237656703929180160 https://twitter.com/topjohnwu/status/1237830555523149824
https://www.androidpolice.com/2020/03/11/safetynet-improvements-kill-magisk-hide/

**Comment by Senliast** [comment]
Oh come on. Google reverted changes (temporary), SN passes again. But with EdXposed enabled it passes sometimes, sometimes not, and that only on Android 10, note, that on Android 9 it passes just without problems. Because if it already passes sometimes - then it's possible to make it pass stable, it's just a small thing somewhere in EdXposed that is not optimized for Android 10, that you should fix. I am sure, you can do it right quickly. Please.

**Comment by MlgmXyysd** [comment]
@Senliast Google reverted, but Magisk not🤷‍♂
