### ISSUE TITLE
[Announcement] No longer allowed to submit issues about SafetyNet

### ISSUE THREAD

**Issue by MlgmXyysd** [ElderDrivers/EdXposed#500]
Reason:

> Google updated SafetyNet check

see: https://twitter.com/topjohnwu/status/1237830555523149824

> The SN test in Magisk Manager is technically *not* a proper attestation. Proper SafetyNet checks will verify results on a remote server, not on device which can be manipulated by code injection frameworks

More details: https://twitter.com/topjohnwu/status/1245956080779198464

Issues submitted about SafetyNet will be closed directly

**Comment by enetec1** [comment]
On my Moto Z2 Force with stock Pie some days ago I suddenly got both CTS & integrity fail, triggered by EdXposed (tested). 
I was on build 4510, but 4523 failed too.
SafetyPatch failed with startup error message ("a problem with device... ").
Updated to EdXposed canary build 4543 solved issue at all, SafetyNet check fully passed and Google Pay working again! 
Great work guys.... ;)

**Comment by second2050** [comment]
To anyone who disabled EdXposed but still fails SafetyNet:
You may need to delete the data of "Google Play Services" and "Google Play Store".
They seem to cache something like an "had (Ed)Xposed installed" flag which needs to be reset to pass SafetyNet again.

**Comment by Justsnoopy30** [comment]
I recommend re-allowing safetynet issues because Google has had their changes reverted for months and we are all passing again. In addition, EdXposed is causing SafetyNet to fail which passes without EdXposed.

**Comment by Justsnoopy30** [comment]
EdXposed is causing both ctsProfile and even basicIntegrity to fail. I hope this is fixed.

**Comment by zacchi4k** [comment]
This may sound crazy... but is it possible EdXposed somehow flips a switch that causes SafetyNet to never ever pass again?
I'm writing this because after installing EdXposed on my phone, it was failing **every single time** with _Response signature validation failed_ even if I did everything I could think of (disabling the module, enabling Magisk Core and even uninstalling Magisk altogether). It's not until I did a wipe and reinstalled both my ROM and Magisk without installing EdXposed afterwards that the issue went away... I know it's really strange but I did the same exact things both times except I didn't install EdXposed

**Comment by crooowned** [comment]
I can confirm what @zacchi4k mentioned

**Comment by jimmy200340** [comment]
same here. install EdXposed lead to Response signature validation fail

**Comment by Justsnoopy30** [comment]
You can fix that after uninstalling/disabling EdXposed by clearing the data of Google Play Services by the way.

**Comment by csin86** [comment]
Has anyone tried SafetyPatcher, this module is new to me, will it work? I'm getting basic integrity and CTS profile match failing due to edxposed on the latest canary build 0.5.0.0

**Comment by Suriyavi** [comment]
Rooting divaice

**Comment by KaMyKaSii** [comment]
Hello guys. I am managing to pass the safetynet check using the last Canary of Edxposed YAHFA. I'm running in blacklist mode, the only different configuration I made was to add all apps with "google" in the package name to the blacklist :p
Maybe someone more patient can add them one by one (and reboot) to find out which one is to blame, it’s probably not any of the Google user apps but I checked them out just because I’m paranoid
![Screenshot_20200701-145011397](https://user-images.githubusercontent.com/17092335/86276433-3cad1800-bbab-11ea-9967-73a0e741c3c3.jpg)
![Screenshot_20200701-144615626](https://user-images.githubusercontent.com/17092335/86276440-3dde4500-bbab-11ea-9ab2-3b18472aa6ee.jpg)
![Screenshot_20200701-144707526](https://user-images.githubusercontent.com/17092335/86276443-3e76db80-bbab-11ea-9369-29ddcea38a0d.jpg)
![Screenshot_20200701-144716266](https://user-images.githubusercontent.com/17092335/86276444-3f0f7200-bbab-11ea-86c9-f2287e36c2c2.jpg)
![Screenshot_20200701-144629325](https://user-images.githubusercontent.com/17092335/86276445-3fa80880-bbab-11ea-97d8-a4388a8f08ad.jpg)
![Screenshot_20200701-144651449](https://user-images.githubusercontent.com/17092335/86276447-3fa80880-bbab-11ea-8516-ab94f16ede14.jpg)
![Screenshot_20200701-144700579](https://user-images.githubusercontent.com/17092335/86276448-40d93580-bbab-11ea-8d47-2f4e6d43936f.jpg)

**Comment by pannal** [comment]
Yeah, the latest canary works for me as well. The device policy in my work profile still detects something, though, I don't know how. Any pointers?

**Comment by nyakze** [comment]
@MlgmXyysd Issue #866 is not related to safetynet problem mentioned here, it was fixed long time ago. Google pay no longer works, it's not just a safetynet bug anymore.
