### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by CROW-14** [ElderDrivers/EdXposed#528]
If I unfortunately activate EdXposed and Google Chrome, it can't be opened, if I turn off the duplicate module and edxposed Google Chrome can be opened again, thanks

**Comment by ayush7gl** [comment]
> If I unfortunately activate EdXposed and Google Chrome, it can't be opened, if I turn off the duplicate module and edxposed Google Chrome can be opened again, thanks

Are you using "HiddenCore" Module??
I also faced this chrome issue using HiddenCore module, i changed the rom and no more issue in that rom, but stock rom has that issue.
Also in stock rom i was using both "HiddenCore" and "No device check" and disabling one of them rectified the issue.

**Comment by CROW-14** [comment]
I don't use the hiden core module, I have problems when using the hiden core module screen time out doesn't work, i'm on havoc rom, thanks

**Comment by mario0318** [comment]
Btw, the always-on display in the HiddenCore module is by design. But there's a post on xda in the Magisk Modules forum, I forget which thread specifically but you can search for it, where somebody repackaged the module apk with the always-on display flag set to false. Give that HC modified apk a try if you need to keep the module for its other features. Uninstall original module first then install modded apk.
