### ISSUE TITLE
[BUG] EdXposed causes crash in Magisk module initialization process

### ISSUE THREAD

**Issue by ValdikSS** [ElderDrivers/EdXposed#569]
**什么情况/What happened?**

When EdXposed module is enabled in Magisk, it causes crash upon loading, which prevents all other modules' late_start service scripts from running.
Magisk log ends with `** boot_complete triggered`, without `Running service.d scripts` or `Running module service scripts`.
You can see `beginning of crash` in the log but without any crash log lines.

Other than that, EdXposed seem to work fine.

If I run `adb logcat` right after the boot, I can see crash lines:

```
--------- beginning of crash
06-15 22:33:53.503  2166  2166 F linker  : CANNOT LINK EXECUTABLE "/system/bin/iptables-wrapper-1.0": library "libbase.so" not found
06-15 22:33:53.515  2167  2167 F linker  : CANNOT LINK EXECUTABLE "/system/bin/ip6tables-wrapper-1.0": library "libdl.so" not found
06-15 22:33:53.520  2168  2168 F linker  : CANNOT LINK EXECUTABLE "/system/bin/iptables-wrapper-1.0": library "libdl.so" not found
```

**Xposed模块列表/Xposed Module List**

No modules, even EdXposed module is not activated.

**Magisk模块列表/Magisk Module List**

Riru Core and Riru EdXposed only.

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: EdXposed v0.4.6.2 (4529) YAHFA (Also tried SandHook and other module versions)

Riru: Riru Core v21.2

Magisk: 20.4 (20400)

**相关Logcat/Logcat**

[EdXposed_Modules_20200615_223612.txt](https://github.com/ElderDrivers/EdXposed/files/4782597/EdXposed_Modules_20200615_223612.txt)
[EdXposed_Verbose_20200615_223616.txt](https://github.com/ElderDrivers/EdXposed/files/4782598/EdXposed_Verbose_20200615_223616.txt)
[magisk_log_20200615_223506.log](https://github.com/ElderDrivers/EdXposed/files/4782599/magisk_log_20200615_223506.log)

And this is Magisk log with EdXposed disabled. You can see that the scripts are starting and no `beginning of crash` log line could be seen.
`adb logcat` does not have any crash lines as well.
[magisk_log_20200615_224008.log](https://github.com/ElderDrivers/EdXposed/files/4782608/magisk_log_20200615_224008.log)

I can also send you `adb logcat` log in private.

**Comment by Crescendo-BLYAT** [comment]
some EdXposed log

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Xiaomi
Brand: Redmi
Device: begonia
Product: begonia
Model: Redmi Note 8 Pro
Fingerprint: Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.2.0.QGGIDXM:user/release-keys
ROM description: begonia-user 10 QP1A.190711.020 V12.0.2.0.QGGIDXM release-keys
Architecture: arm64-v8a
Android build: QP1A.190711.020
Android version: 10
Android sdk: 29
EdXposed version: v0.5.0.6_4569-android_r (YAHFA)
EdXposed api: 91.0
Riru version:  ()
Riru api: 
Magisk: 20.4 (20400)
--------- beginning of main
--------- beginning of system
--------- beginning of crash
11-26 22:15:46.014   722   722 I EdXposed-Bridge: Loading modules from /data/app/name.mikanoshi.customiuizer-QWB1B5GQ0qkFlmE45nFaHQ==/base.apk
11-26 22:15:46.040   722   722 I EdXposed-Bridge:   Loading class name.mikanoshi.customiuizer.MainModule
11-26 22:15:46.471   722   722 I EdXposed-Bridge: Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-CYyfIC7sXaLbsDpZJW0E2w==/base.apk
11-26 22:15:46.478   722   722 I EdXposed-Bridge:   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
11-26 22:15:46.599   722   722 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-Ghb_PNp1TvTRylae4NslXQ==/base.apk
11-26 22:15:46.753   722   722 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
11-26 22:15:46.754   722   722 I EdXposed-Bridge: Loading modules from /data/app/com.xposed.miuianesthetist-GXoJsp5FrT733wR9OaLdFA==/base.apk
11-26 22:15:46.761   722   722 I EdXposed-Bridge:   Loading class com.xposed.miuianesthetist.DisableSecurityCheck
11-26 22:15:46.762   722   722 I EdXposed-Bridge: Loading modules from /data/app/ru.dImelAjZ.HurvfEfwL-uA0-49eGpmc59-UCtKF2dQ==/base.apk
11-26 22:15:46.873   722   722 I EdXposed-Bridge:   Loading class com.xposed.XSupport
11-26 22:15:46.943   722   722 I EdXposed-Bridge: Loading modules from /data/app/com.marz.instaprefs-bHmAXuqg-mcflsniriYY3g==/base.apk
11-26 22:15:47.099   722   722 I EdXposed-Bridge:   Loading class com.marz.instaprefs.HookMethods
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.server.notification.NotificationManagerService#enqueueNotificationInternal(java.lang.String,java.lang.String,int,int,java.lang.String,int,android.app.Notification,int[],int)#exact
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.XposedMod.handleLoadPackage(XposedMod.java:344)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:18)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:539)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:374)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
11-26 22:15:47.999  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:973)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.server.pm.PackageManagerService#grantPermissionsLPw(android.content.pm.PackageParser.Package,boolean,java.lang.String)#exact
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.hooks.PackagePermissions.initHooks(PackagePermissions.java:100)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.XposedMod.handleLoadPackage(XposedMod.java:352)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:18)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:539)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:374)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
11-26 22:15:48.009  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:973)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.am.ActivityStackSupervisor
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:299)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.hooks.Activities.hookActivitySettingsInSystemServer(Activities.java:251)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.XposedMod.handleLoadPackage(XposedMod.java:353)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:18)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:539)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:374)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:973)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.android.server.am.ActivityStackSupervisor
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.Class.classForName(Native Method)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.Class.forName(Class.java:454)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	... 14 more
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.android.server.am.ActivityStackSupervisor
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	... 18 more
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.am.ActivityRecord
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.hooks.Activities.hookActivitySettingsInSystemServer(Activities.java:281)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.mods.appsettings.XposedMod.handleLoadPackage(XposedMod.java:353)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:18)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:539)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:374)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:973)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.android.server.am.ActivityRecord
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.Class.classForName(Native Method)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at java.lang.Class.forName(Class.java:454)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	... 13 more
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.android.server.am.ActivityRecord
11-26 22:15:48.011  1279  1279 E EdXposed-Bridge: 	... 17 more
11-26 22:16:01.907   725   725 I EdXposed-Bridge: Loading modules from /data/app/name.mikanoshi.customiuizer-QWB1B5GQ0qkFlmE45nFaHQ==/base.apk
11-26 22:16:01.983   725   725 I EdXposed-Bridge:   Loading class name.mikanoshi.customiuizer.MainModule
11-26 22:16:02.587   725   725 I EdXposed-Bridge: Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-CYyfIC7sXaLbsDpZJW0E2w==/base.apk
11-26 22:16:02.593   725   725 I EdXposed-Bridge:   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
11-26 22:16:02.751   725   725 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-Ghb_PNp1TvTRylae4NslXQ==/base.apk
11-26 22:16:03.051   725   725 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
11-26 22:16:03.052   725   725 I EdXposed-Bridge: Loading modules from /data/app/com.xposed.miuianesthetist-GXoJsp5FrT733wR9OaLdFA==/base.apk
11-26 22:16:03.054   725   725 I EdXposed-Bridge:   Loading class com.xposed.miuianesthetist.DisableSecurityCheck
11-26 22:16:03.055   725   725 I EdXposed-Bridge: Loading modules from /data/app/ru.dImelAjZ.HurvfEfwL-uA0-49eGpmc59-UCtKF2dQ==/base.apk
11-26 22:16:03.260   725   725 I EdXposed-Bridge:   Loading class com.xposed.XSupport
11-26 22:16:03.349   725   725 I EdXposed-Bridge: Loading modules from /data/app/com.marz.instaprefs-bHmAXuqg-mcflsniriYY3g==/base.apk
11-26 22:16:03.650   725   725 I EdXposed-Bridge:   Loading class com.marz.instaprefs.HookMethods
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: java.lang.ArrayIndexOutOfBoundsException: length=1; index=4
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at com.xposed.XSupport$11.beforeHookedMethod(XSupport.java:600)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:94)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at com.android.server.pm.PackageInstallerSession.commitNonStagedLocked(PackageInstallerSession.java:1371)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at com.android.server.pm.PackageInstallerSession.handleCommit(PackageInstallerSession.java:1325)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at com.android.server.pm.PackageInstallerSession.access$1000(PackageInstallerSession.java:133)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at com.android.server.pm.PackageInstallerSession$3.handleMessage(PackageInstallerSession.java:380)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
11-26 22:50:51.678  1279  1587 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main
--------- beginning of system
--------- beginning of main

**Comment by kotori2** [comment]
@ValdikSS The crash log doesn't include any crash. 
`CANNOT LINK EXECUTABLE "/system/bin/iptables-wrapper-1.0"` means your phone manufacture messed up with `iptables-wrapper-1.0`, its not related to EdXposed at all.

**Comment by kotori2** [comment]
@Crescendo-BLYAT The log you provided belongs to `com.marz.instaprefs`. We don't accept module specific error here.
