### ISSUE TITLE
[BUG] Bootloop without coredomain's sepolicy

### ISSUE THREAD

**Issue by yujincheng08** [ElderDrivers/EdXposed#688]
This is because we install inline hooks in `onModuleLoad`, where we are in the `coredomain`, and inline hooks require `execmem` permission (workaround: add `allow coredomain coredomain process execmem` to `sepolicy.rule` or delete `sepolicy.rule` completely).

We don't want to add any sepolicy about the `coredomain`, so we are planning to move inline hooks to post fork.

This problem happens on Android P or older devices mostly.

[logcat2.txt](https://github.com/ElderDrivers/EdXposed/files/5610236/logcat2.txt)

**Comment by enetec1** [comment]
Verified that the last release without the bug is 4569.
4570 & 4571 are not available for download and since 4572 I have bootloop on Android P.

**Comment by EWF54Y6U7I** [comment]
![OGFZZ37XNK)V`ENF3YMSF@V](https://user-images.githubusercontent.com/55339634/100536711-55565280-325d-11eb-8704-4b401f672c59.jpg)

**Comment by 1024mb** [comment]
In EMUI8 the workaround doesn't work, I'm using Riru v22.4 and Sandhook, adding `allow coredomain coredomain process execmem` to sepolicy still bootloops, deleting sepolicy contents also still bootloops, as they are workarounds I don't imagine you want logcats?

**Comment by kotori2** [comment]
Fixed via d6c7570588b9c1b6ff2393429d8f5c6a44c3e552

**Comment by yujincheng08** [comment]
Fix in https://github.com/ElderDrivers/EdXposed/commit/1e9b307f5451dacd6b3c1a46e7e26cb23579e777 and https://github.com/ElderDrivers/EdXposed/commit/d6c7570588b9c1b6ff2393429d8f5c6a44c3e552

**Comment by 1024mb** [comment]
I've installed latest canary with Magisk v21.1 and Riru v22.4 and now it doesn't bootloops but the manager doesn't detects the framework. I've rebooted 4 times and nothing. This is the EdXposed log: 
[EdXposed_Verbose_20201203_142742.txt](https://github.com/ElderDrivers/EdXposed/files/5638496/EdXposed_Verbose_20201203_142742.txt)

I can't enable EdXposed on the modules list because it says that no framework is installed, although in the manager main screen it says that the framework is installed but not active.

<details>

![photo_2020-12-03_14-44-10](https://user-images.githubusercontent.com/9301204/101080256-7510b200-35a0-11eb-8a9d-5525495391a3.jpg)

![photo_2020-12-03_14-44-15](https://user-images.githubusercontent.com/9301204/101080265-7a6dfc80-35a0-11eb-8eaa-9b7fc4631d05.jpg)

</details>

**Comment by kotori2** [comment]
@1024mb Check the pinned FAQ.

**Comment by 1024mb** [comment]
> 
> 
> @1024mb Check the pinned FAQ.

I saw the FAQ but it says that the point 2 should only happen in Android R, I'm in Android Oreo (8.0.0) with EMUI 8. I will try with YAHFA.

**Comment by kotori2** [comment]
<img src="https://user-images.githubusercontent.com/17663689/101082478-79f85480-35e6-11eb-8c1f-ad39c639cd31.png" data-canonical-src="https://user-images.githubusercontent.com/17663689/101082478-79f85480-35e6-11eb-8c1f-ad39c639cd31.png" width="50" height="45" /> That's weird, but maybe gonna test it later.

**Comment by enxg** [comment]
Any updates on EMUI 8 support?
