### ISSUE TITLE
[Bug] Ignored and Serious Bug

### ISSUE THREAD

**Issue by shah-95** [ElderDrivers/EdXposed#697]
Respectfully to the devs,

I know this has been in the knowledge and you've done an announcement in this regard, but I would really love if the respected devs can give a transparent and clear cut answer to the questions. I wanted to post this on the riru github too. But I preferred to post with the original dev first..

1. Why such a big issue has been downplayed, neglected, ignored and placed at a side when its really apparent that latest stable riru core v22 does not gets recognized and it breaks the ed-exposed functionality totally for the 100% users out there using the ed-exposed stable channel..

2. Why its considered as an invalid or stupid issue or banning people asking about this ? When it clearly makes the latest stable build as 'totally non-working'

3. Why still no stable build has been released to address this app-breaking issue ? Even its more then half a month into this..

4. Why it was expected to install the latest canary build instead of a fixed stable version ? When not everyone wants to get a highly unstable canary build running on their daily-driver phones and getting in potential problems when instead the stable version should have been fixed ?

5. Why users were forced to install through unstable canary channel to 'just' get ed-exposed working with riru v22+ ? Instead of a fixed stable channel ? 

6. Did ed-exposed devs didn't knew that riru core v22 was released through stable channel towards all users using magisk which broke ed-exposed for 100% of users out there on ed-exposed stable channel?

7. Why was respected developers for both riru and ed-exposed behaved in such a weird and erratic way of banning people and labelling a serious and legit issue like this as invalid and stupid ?

8. Why all the issues created around this were marked invalid and closed when in reality it broke functionality for 100% of users on ed-exposed and riru stable channels ?

9. Why the first announcement of such big issue was made only 4 days ago on github and nothing official on it on any magisk documentation or a warning to anyone who updates riru core through magisk or any xda heads up post ? And still to this date no fixed stable version is available ? When this issue has been present since more then half a month ..

Respected Devs, your efforts for bringing ed-exposed to users is really great but a great software is due to its users, me and all others suffering from this issue would love to see this issue fixed for the stable channel, but what was done till now was really strange and unprofessional by such great devs like you. My best wishes to see this issue get sorted out as soon as possible. And feel free to mark this as an invalid or stupid question too, Sar :)

Regards.

**Comment by yujincheng08** [comment]
1. riru 22 has a great change: it changed its injecting strategy so ALL old riru modules cannot detect riru 22, which is expected including EdXposed.
1. Because in the pinned FAQ issue, we clarify how to get EdXposed works on riru22.
1. As said, riru22 has a great change. The timing it inject has been changed and EdXposed has to modify its behavior greatly to get compatible. Like, we cannot get the `ClassLinker` pointer because the loaded time of EdXposed has postponed.
1. As said, the behavior has changed and we need to enough time until we push it to stable channel.
1. As said, the behavior has changed. No simple 'fix' to be compatible with riru22.
1. We definitely knew it. That's why there is a pinned issue talking about this.
1. Because those are definitely stupid issues. They thought compatibility to riru22 is very simple and force us to do a quick fix of it. But no. They know nothing about the coding and mechanism of riru22, but pouring spam, stupid and repeated issues on the same problem.
1. As said, no quick fix for stable channel.
1. Changelog of riru22 has clarified that ALL modules need to do corresponding modification for compatibility. And it's clearly that EdXposed has not announced update after riru 22 released. So 100% people with functional brain know EdXposed will break down if they upgrade riru22.

You know, we did tons of works to be compatible with riru22 and we have to test it carefully, otherwise, tons of user will report bootloop on the same issue and it's tedious to handle them. If there were a simple fix for compatibility to riru22, we would definitely do the fix in the pre-release stage of riru22. The best way of contribution is issue with logcat or even pull requests of fixing issue, instead of COMPLAINS. This issue is definitely another spam and stupid issue that should be closed and locked.

**Comment by terrytw** [comment]
Coming from Rikka himself:

> Because of this, all modules must change. If your module hasn't updated, ask the module developer to make changes. For 99% modules, this is super easy.

> Riru's API change has stabilized from 2020-10-11, it's long enough

Also, riru v22 has been pushed to magisk official repository, there is no changelog for each module. Many just clicked "update" in magisk manager app. 

Many chose "stable" release channel for a reason. They expect things to work, or at least not broken for everyone. 

But again, this is an open source project without any real benefits behind it, the devs could have abandoned it any time as they wish. But I hope it could be coordinated better, after all, they were not blindfolded by this riru update, they knew about it.

**Comment by yujincheng08** [comment]
Yes. 99% modules are easy to update, but unfortuenately, not including EdXposed.

**Comment by shah-95** [comment]
![Screenshot_20201130-100141](https://user-images.githubusercontent.com/25111008/100570689-28ed1580-32f3-11eb-841c-889107487907.jpg)
Please enlighten me dear Sar, where does it says that it will break ed-exposed totally ? And how can I know in advance if ed-exposed is broken or not? Unless I'm a developer myself.. but you cannot expect a developer's level of knowledge for 99% of tech savvy people out there..

Also the pinned post only mentions to update to canary builds ? But don't you see the critical issue that all users on stable channel are screwed and that's the very reason you get all the repeated spams because 100% of stable branch is suffering this and all you say is 'just update to canary builds' when we choose stable version for 'stability' in first place like terry said and not everyone wants to install a canary build with a clear warning written "it will be highly unstable" and "use it on your own risk" 
Do you really expect that all 'stable channel base of users' would migrate to 'canary channel' ?

And you are asking a user to contribute when the respected devs didn't bothered to write a single thing regarding this issue .. until some 4 days ago.. again which just says to update to canary builds.. 

So yes a user should contribute with logs and all that but did the respected devs even made any announcement on xda or here on github when riru v22 was first released to stable magisk channel ? No

Did the update changelog mentioned that it'll break ed-exposed stable functionality? No

And I respect devs tremendously, but please stop judging the users that they 'didn't read the changelogs and such bla bla'.. all the users who have made this far in rooting through magisk, installing custom kernels and roms and customizing through xposed, substratum and many others prior to ed-exposed are 99% tech savvy and know very well how to read changelogs :)

Also all that the riru update v22 changelog ever mentioned was "it will be super easy to be fixed for 90% modules out there"

Now how could we know the future unless the devs themselves told us of the issue and all the necessary logs they required even before the issue would have made to the general user base.

If that's all about it, to just mark legit concerns when 100% stable channel base is screwed - as spam and stupid, then respectfully I won't waste any more of your's or mine time and save you the hassle of closing this thread.

Regards,
Shah22, xda-devs

**Comment by yujincheng08** [comment]
ALL modules shold be changed. You should have noticed that. Isn't edxposed a riru module? PLZ use ur brain.

And for the stable channel issue, as I said multiple times, NO stable fix and thats why we test compatibility on canary channel first.

We dont expext user to update to canry channel. YOU CAN DOWNGRADE RIRU right? I think we don't have to tell you about downgrading because anyone with functional brain see canary is reuiqred for riru 22 they will choose to upgrade to canary or downgrade riru. 

Not only edxposed, many other riru modules are not compatibe with riru 22. And EdXposed is one of the first modules to do riru22 compatiblilty. You ignored our efforts and keep compalining about the stable channel issue.

We dont know when the stable version can be released. We are also want to dig out and fix all bugs and release a stable version ASAP. But we are not god. How could we finish it in short time?

Stop arguing about it. It wins nothing but tear out paitence of devs. You are watsing our time which is supposed to spend on fixing bug on riru 22 version.
