### ISSUE TITLE
[BUG] 日志文件内容缺失

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#761]
riru 23
edxposed 0.5.1.3_4648-master
android 11
edxposed 460

最新版的日志里似乎缺少了 xposedbridge的异常
比如hook方法没找到  hook的类没找到之类的
```logcat | grep xposed``` 可以找到这些异常

**Comment by coderstory** [comment]
```start_log_cather error "XSharedPreferences:V EdXposed-Bridge:V" true true```

tag对不上导致没有输出

![photo_2020-12-25_09-55-43](https://user-images.githubusercontent.com/11525359/103113846-6dbc6000-4697-11eb-9ea4-e30990ac6e11.jpg)

**Comment by MlgmXyysd** [comment]
System.err:W 不属于 EdXposed 的日志范围

**Comment by coderstory** [comment]
> `System.err:W` 不属于 EdXposed 的日志范围

不打印出来的话 ，开发调试插件就比较麻烦了

**Comment by MlgmXyysd** [comment]
> > `System.err:W` 不属于 EdXposed 的日志范围
> 
> 不打印出来的话 ，开发调试插件就比较麻烦了

请使用 [`de.robv.android.xposed.XposedBridge.log(java.lang.String)`](https://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#log(java.lang.String)) 或 [`de.robv.android.xposed.XposedBridge.log(log(java.lang.Throwable))`](https://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#log(java.lang.Throwable)) 打印日志

**Comment by coderstory** [comment]
> > > `System.err:W` 不属于 EdXposed 的日志范围
> > 
> > 
> > 不打印出来的话 ，开发调试插件就比较麻烦了
> 
> 请使用 [`de.robv.android.xposed.XposedBridge.log(java.lang.String)`](https://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#log(java.lang.String)) 或 [`de.robv.android.xposed.XposedBridge.log(log(java.lang.Throwable)`](https://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#log(java.lang.Throwable)) 打印日志

不是这东西 啊。。。这个是主动打印日志。。。用这个的话 所以的hook  我都要try catch 然后主动打印了

原本  更新支持R之前 日志里不是有xposed的异常记录么

**Comment by canyie** [comment]
你指的是在handleLoadPackage等方法里抛出的异常不会被打印到log里了？

**Comment by blackbox87** [comment]
Issue: https://github.com/ElderDrivers/EdXposed/issues/527
Fixed: https://github.com/ElderDrivers/EdXposed/commit/395185ad1054b32785eb3f99457a6a39d0865d02

You're supposed to use try & catch in your own module so that each exception is handled correctly, otherwise EdXposed could flood the log file with pointless messages. Just look at [GravityBox](https://github.com/GravityBox/GravityBox/blob/q/GravityBox/src/main/java/com/ceco/q/gravitybox/ResourceProxy.java#L102-L110), [XHangouts](https://github.com/kmark/XHangouts/blob/master/app/src/main/java/com/versobit/kmark/xhangouts/mods/UiQuickSettings.java#L106-L113), [CustoMIUIzer](https://code.highspec.ru/Mikanoshi/CustoMIUIzer/src/branch/master/app/src/main/java/name/mikanoshi/customiuizer/mods/System.java#L187-L190), [XCallRecording](https://github.com/iptux/XCallRecording-xposed/blob/master/app/src/main/java/net/iptux/xposed/callrecording/ModCallRecording.java#L77-L90) or [Firefds Kit](https://github.com/Firefds/FirefdsKit/blob/pie/firefdskit/src/main/java/sb/firefds/pie/firefdskit/Xposed.java#L58-L65).

Alternatively compile your own version of SandHook with debug logging enabled.
